library_manager.App/Models/BooksListViewModel.cs
using System;

namespace library_manager.App.Models
{
    public class BooksListViewModel
    {
        public Guid BookId { set; get; }
        public string BookName { get; set; }
    }
}

library_manager.App/Controllers/BookController.cs
using System;
using System.Linq;
using library_manager.App.Models;
using library_manager.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace library_manager.app.Controllers
{
    public class BookController : Controller
    {
        private readonly DatabaseContext _databaseContext;

        public BookController(DatabaseContext databaseContext)
        {
            _databaseContext = databaseContext;
        }

        [HttpPost]
        public IActionResult BookView(Guid id)
        {
            var book = _databaseContext.Books.FirstOrDefault(x => x.BookId == id);

            return View(new BookViewModel
            {
                BookName = book.BookName,
                Descriptions = book.Descriptions,
                Category = _databaseContext.Category.FirstOrDefault(x => x.CategoryId == book.CategoryId)
                    ?.CategoryName,
                Author = _databaseContext.Author.FirstOrDefault(x => x.AuthorId == book.AuthorId)?.Firstname + " " +
                         _databaseContext.Author.FirstOrDefault(x => x.AuthorId == book.AuthorId)?.LastName
            });
       }
    }
}

library_manager.App/Controllers/BooksListController.cs
using System;
using System.Linq;
using library_manager.App.Models;
using library_manager.App.Services;
using library_manager.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace library_manager.App.Controllers
{
    public class BooksListController : Controller
    {
        private readonly DatabaseContext _databaseContext;

        public BooksListController(DatabaseContext databaseContext, BookService bookService)
        {
            _databaseContext = databaseContext;
        }

        public IActionResult BooksListView(int pageIndex = 1, int pageSize = 10)
        {
            var books = _databaseContext
                .Books
                .OrderBy(b => b.BookName)
                .Skip((pageIndex - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            
            var categories = _databaseContext.Category.ToList();
            var authors = _databaseContext.Author.ToList();

            var model = books.Select(book => new BooksListViewModel
            {
                BookId = book.BookId,
                BookName = book.BookName
            }).ToList();

            ViewBag.CurrentPage = pageIndex;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalCount = _databaseContext.Books.Count();

            int totalPages = (int)Math.Ceiling((double?)(ViewBag.TotalCount ?? 0) / (ViewBag.PageSize ?? 1));
            ViewBag.TotalPages = totalPages;

            return View(model);
        }
        
        [HttpPost]
        public IActionResult RemoveBookForm(Guid id)
        {
            var book = _databaseContext.Books.First(x => x.BookId == id);
            _databaseContext.Remove(book);
            _databaseContext.SaveChanges();

            return RedirectToAction("BooksListView");
        }
    }
}

library_manager.App/Controllers/EditBookController.cs
using System;
using System.Linq;
using library_manager.App.Models;
using library_manager.App.Services;
using library_manager.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace library_manager.App.Controllers
{
    public class EditBookController :Controller
    {
        private readonly DatabaseContext _databaseContext;
        private readonly BookService _bookService;

        public EditBookController(DatabaseContext databaseContext, BookService bookService)
        {
            _databaseContext = databaseContext;
            _bookService = bookService;
        }
        
        [HttpPost]
        public IActionResult EditBookView(Guid id) {
            var book = _databaseContext.Books.First(x => x.BookId == id);
            var authorViewModels = _bookService.GetAuthorViewModels();
            var categoryViewModels = _bookService.GetCategoryViewModels();

            return View("EditBookView", new EditBookViewModel
            {
                BookId = book.BookId.ToString(),
                BookName = book.BookName,
                Descriptions = book.Descriptions,
                CategoryId = book.CategoryId.ToString(),
                AuthorId = book.AuthorId.ToString(),
                
                Authors = authorViewModels,
                Categories = categoryViewModels,
            });
        }

        [HttpPost]
        public IActionResult SaveChanges(EditBookViewModel model)
        {
            var book = _databaseContext.Books.First(x => x.BookId == Guid.Parse(model.BookId));
    
            if (book != null)
            {
                book.BookName = model.BookName;
                book.Descriptions = model.Descriptions;
                book.CategoryId = Guid.Parse(model.CategoryId);
                book.AuthorId = Guid.Parse(model.AuthorId);
        
                _databaseContext.SaveChanges();
            }
    
            return RedirectToAction("BooksListView", "BooksList");
        }
    }
}

library_manager.App/Views/BooksList/BooksListView.cshtml
@model List<BooksListViewModel>

@{
    ViewBag.Title = "Books list";
    Layout = "_Layout";
    int totalPages = (int)Math.Ceiling((double?)(ViewBag.TotalCount ?? 0) / (ViewBag.PageSize ?? 1));
    
}
@if (Model != null)
{
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
            <th>Edit</th>
            <th>Remove</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>
                    @book.BookName
                </td>

                <td>
                    <form asp-action="BookView" asp-controller="Book" asp-route-id="@book.BookId">
                        <button type="submit">See more</button>
                    </form>
                </td>

                <td>
                    <form asp-action="EditBookView" asp-controller="EditBook" asp-route-id="@book.BookId">
                        <button type="submit">Edit</button>
                    </form>
                </td>

                <td>
                    <form asp-action="RemoveBookForm" asp-route-id="@book.BookId">
                        <button type="submit">Remove</button>
                    </form>
                </td>

            </tr>
        }
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @for (int i = 1; i <= totalPages; i++)
            {
                <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
                    <a class="page-link" href="@Url.Action("BooksListView", new { pageIndex = i, pageSize = ViewBag.PageSize })">@i</a>
                </li>
            }
        </ul>
    </nav>
}
else
    {
    <p>No books available.</p>
                            
    }