library_manager.App/Controllers/AddBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using library_manager.App.Models;
using library_manager.App.Services;
using library_manager.Domain;
using library_manager.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace library_manager.App.Controllers
{
    public class AddBookController : Controller
    {
        private readonly DatabaseContext _databaseContext;
        private readonly BookService _bookService;
        
        public AddBookController(DatabaseContext databaseContext, BookService bookService)
        {
            _databaseContext = databaseContext;
            _bookService = bookService;
        }
        
        public IActionResult AddBookView()
        {
            var authorViewModels = _bookService.GetAuthorViewModels();
            var categoryViewModels = _bookService.GetCategoryViewModels();
            
            var addBookViewModel = new AddBookViewModel
            {
                Authors = authorViewModels,
                Categories = categoryViewModels
            };

            return View(addBookViewModel);
        }

        [HttpPost]
        public IActionResult AddBook(AddBookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var authorViewModels = _bookService.GetAuthorViewModels();
                var categoryViewModels = _bookService.GetCategoryViewModels();
            
                var addBookViewModel = new AddBookViewModel
                {
                    Authors = authorViewModels,
                    Categories = categoryViewModels
                };

                return View("AddBookView", addBookViewModel);
            }

            var book = new Book
            {
                BookName = model.BookName,
                Descriptions = model.Descriptions,
                AuthorId = Guid.Parse(model.AuthorId)
            };

            _databaseContext.Add(book);
            _databaseContext.SaveChanges();

            return RedirectToAction("BooksListView", "BooksList");
        }
    }
}

library_manager.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Library manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                Library manager
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="AddBook" asp-action="AddBookView">Add book</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="BooksList" asp-action="BooksListView">Books list</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

@if ((string)ViewData["Title"] != "Home Page")
{
    <nav class="breadcrumb hidden-sm-down">
        <div class="container">
            <h1 class="text-center">@ViewData["Title"]</h1>
            <ol>
                <li class="breadcrumb-item">
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <span class="separator"> / </span>
                <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
            </ol>
        </div>
    </nav>
}

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Library manager. Realization - <a asp-area="" asp-controller="Home" asp-action="Contact">Bartosz Kluska</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)

</body>
</html>